## DATASET CHECK

In [1]:
import pandas as pd
import string

In [3]:
# all_letters = string.ascii_letters + "0123456789 .,;'-_()[]@*$#%?!^<>\"`=+&~|:/\\"
all_letters = string.digits + string.ascii_letters + string.punctuation + '\n'

In [4]:
all_letters

'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~\n'

In [ ]:
filename = r'Dataset/all.txt'
text = []

In [79]:
with open(filename) as f:
    lines = [line.rstrip('\n') for line in f]

In [80]:
lines

['rlkj@1980',
 'tp@12345678',
 'M!$$y2005',
 'IM1n1raq!!',
 'n#wlif07',
 'acorn123!',
 '521@843',
 '500049@vikas',
 'Ranger#2',
 'sw33tb@by',
 'dod896@l1',
 'India@123456',
 'tvicky_38',
 '55296 -',
 'adr_123',
 '5.bigdog.6',
 'Por$c#301',
 'Jay1026.',
 'queens-08',
 'Ma%%32Fn',
 '12-guage',
 'Slvr540!!',
 'Aziza@444',
 'xyzzy@42',
 'ABcd!@3456',
 '141414!',
 '!7Eezbutz',
 'komal@1889',
 'atl678*',
 'sarabeee#0',
 'aghg.d]hk123',
 'Max$56li',
 'lexi01*',
 'spike10^',
 'riz_123',
 '*mineonly1',
 'fucker-8',
 'v-dogg651',
 'nannu_333',
 'shift_1',
 'yankee1!',
 '@>-; j2',
 'JAIMINE.18301',
 'Hmfogtliwt1!',
 'vmfa=332',
 'Randy&Ann1',
 '1qaz@WSX3edc',
 '$ow3ll01',
 'dilldo_41364',
 'n@t@li3',
 'mustang87*',
 'maxie_115',
 '69longpole^',
 'ang#1010',
 '12!@asAS2',
 '*deniro321*',
 'integra_11',
 '06.08.74',
 '111111a/b',
 '$rwm1446',
 'Yz250cc!',
 'EL.rjel.78',
 'b@dbon352',
 '390fs((@*',
 'supri@24',
 'St3mmen/',
 'N1chola$',
 'MGoyet57^$',
 'Massive1!',
 '$up3rm2n69',
 'P@$$w0rd',
 '430WRANSOM*',
 '$1dexter',
 'Mindy777!',
 'BADASSBOSS1.',
 'bjme69*',
 'vicho_12',
 'kimmy@91',
 'hz9824$$77',
 '*pkdll79',
 'hgregs5@hotmail',
 '`1- equals `1- equals',
 '200000**',
 'zaiba*786',
 'Keg99!!',
 'Mash_217',
 '!234Qwer',
 '#o9bawl2g0',
 'ibtrg_05',
 'Q1w2E3r4)',
 'DCwhat#1',
 '#1Gangster',
 'lled83!',
 'subodh.com23',
 'Defygravity#4',
 'Mwss1722!',
 'luvvvv.1',
 '(wolf)69',
 'Pa$$word11',
 'purush@9',
 'r2!@roya',
 'samoth@22',
 'abhinav$08',
 '!JM4223jm!',
 'khush@24ab',
 'DAwn2538!!',
 'TsL0404**',
 'ric_rock63',
 'amber04@',
 'idiot@123',
 'munaiba.23',
 'Carol1985$$$',
 'hockey4life!',
 'abc123@',
 'tacoma#12',
 'love143143*',
 '$cotL4nd',
 'Red0078!',
 'Kfce!525',
 '2212@fire',
 'maruti.3639',
 'qwerty#1',
 'Tommy#1',
 '#811gpd',
 'pyyhx#1',
 'camcam_09',
 '6969)()()(',
 'leska_0215',
 'NM0x!ey1n',
 'don@2003',
 '$R0adRa!l',
 'CCllmm81!!',
 '*p#1672!',
 'fab5bros.',
 'Dmlss%30',
 '1234$abc',
 'tepas8586@123',
 'tamokce56.25',
 'seema!1',
 'Shawn#36',
 'Ah$511977',
 'ac/dc43122',
 '#1hottie',
 '2007-08',
 'A11is0n@',
 '1234@abcd',
 'Cowboys#1',
 'rolnosik_39',
 'fazuha@143',
 '2RDK4Men*',
 'Firedawgs10!',
 '**JH55ds',
 'df45DF$%',
 'Db3**1234',
 'ewei^4TR',
 '91-zephyr',
 '12345ama@',
 'moscow01!',
 'lance2lot#',
 'i8@cbgbs',
 '456%sexy',
 '!1bigkahuna',
 '24aug88@$',
 'W@ndagr8',
 'dragon!1',
 'chicano4?',
 '@ROSE1234',
 'fun.123',
 'shawna_1',
 'cathym1#',
 'pa28-180',
 'medo.01',
 'Skooter71$',
 'chint00$',
 'Microsoft123!',
 'Jimmy22!',
 'Iailwm2c1!',
 'bettisy-boy5',
 'R0Dgerth@!',
 '9$ether',
 'M@cEt0wn!',
 'm@dhur40i',
 'trista_03',
 'c00L1#?mAN',
 'swingtown@11',
 'lavecious16-alr',
 'qH3M;Ppp',
 'Ghar*usa2',
 ';outu4458',
 '11ju1994_11ju94',
 'Mca333d@',
 '2wsx@WSX',
 'Rsa21oct85$',
 'red#2008',
 'equator@1',
 'larry/mary3',
 'bu*res.29',
 '82870002.Hkem',
 'goldfish1!',
 'Err:520',
 'kombucha95%',
 'Ilgeah*1965',
 'property925@',
 'men@123',
 '123456@78',
 'spf23@yahoo.com',
 'tps@970',
 'sh@wn66',
 '94639-44149',
 'Ramona!84',
 'JUNE233/',
 'I<3LB2def',
 'tt&atti2dd',
 'Rama.l11',
 '5david$$',
 'c@ndyc0rn',
 'fuckYou2$ME',
 'asd123.',
 'mouc@143',
 '^YHN9ol.',
 'zaq1@WSX',
 'KBrandon!#fox30',
 '7yhnMJU^',
 'halo-1903',
 'jBy&m87',
 '?06rbpy?',
 '15V@ndalia',
 'f@c3tim3',
 '1234!@#$a',
 'hater123!',
 'ahabs_99',
 'TRoy40$$',
 'jesseno.1',
 '12.11.74',
 '275/40/20',
 'dalejr#8',
 '76-2o0s0u2a',
 'M1keyb-1969',
 'buddy123*',
 'bru!va08',
 '!Pass1234',
 'Mandy@82',
 'kaais_86',
 'pot_420',
 'bipi@123',
 '!QAZxsw2',
 'BudR1z0r!!',
 'Dozzer45*',
 'Kz@92Q*>',
 'K1ttyC@T',
 '6yhn9ol.',
 'p!p32008',
 'CR08#$sr',
 'F0ufcfk!',
 '2403@doniztss',
 'live4God!',
 'pascode150!',
 'psi.1234',
 'april12345%%%',
 'in-1289',
 'lilangie#44',
 'mountain!1',
 'R@N#er45!',
 'Monkey1!',
 'happy!7777',
 'Bubba#456',
 '@ries21',
 '#10jessy',
 'boswell#1',
 'newlife0-1',
 'Splinky#69',
 '##Laverne1$',
 'sukoi123$',
 '21.613.138',
 'kia12345%%',
 'LONGINUS_14',
 '%c0tt543',
 'ngf0607!',
 'lucky2503!',
 'hojo34*',
 'calif_cpl2001',
 '44kats!2',
 'boss143*',
 'ilha&69',
 'rum@t80!YO',
 'max002@',
 'j3ffr3y98-bailey',
 'bamaboy#1',
 'clint4268!',
 'Purple.123',
 'bigal#87',
 'qotsa1978!@',
 'mjmj@06',
 'manoj*28',
 'jeiger#24',
 'Suryam_1985',
 'dave@dave1',
 'rocking_193',
 'reyess_88',
 'kelvic_13',
 'imakat0653@yahoo.com',
 'susilar$84',
 'summer@69',
 'Jskr!975',
 'location-s1',
 'Brooke*1',
 'fuckunow$5',
 'Ch!ck3ns',
 'sar03ge#1',
 'TTking74$$',
 'lovers123*',
 'rna.252',
 'dlm@15937',
 'black_c0ck',
 'rfg-0800',
 'dwl@1320',
 '..  09125875162',
 'Bulldog89*',
 'Kingbud#1',
 'jatt123@',
 'iloveronan23!',
 'matcu-69',
 'Smurf.74',
 'baseball#1',
 'sambo_el_11',
 '##army89',
 'no1is@@',
 'KRtr4454#',
 'REbecca!@34',
 'B@ubacart1',
 '#EDC4rfv',
 '138*438',
 '11yhtak*',
 'usmc_3075',
 '!Dalejr88',
 'henley*1',
 'Aczs@b#4',
 'coldwell1*',
 'sunils$0',
 'p@ssw0rd',
 '300resumes?',
 'monse12@',
 'TellNo1!',
 '118241$',
 'ORLY1-9-59',
 'moNTan34#$',
 '021869*',
 'Bi@Tch72',
 'jb-90252',
 'H&H5050',
 'snow*03',
 '1Spyder.',
 '$secco77a',
 'P@ssword8',
 'US.army.44',
 'salhji45*',
 '02Bdays2#',
 '$imple6',
 'ab1g@il',
 'durango_12',
 'ssmsswjw@1',
 '987654321!',
 'neeru47301@',
 '496/6206',
 'b@ndit04',
 'BuckI208!!',
 '9o0p(O)P',
 '$4licks',
 'M4ld1ves@123',
 '4getmenot.hs',
 '17candle000$',
 'Dolphin.1',
 'viking2-7',
 '96JPcher#1',
 '#2always',
 '21L-TL-T',
 '5.7cross',
 'bombay@123',
 'Kill$20',
 'spice_1',
 '*Try08*',
 'makayla3*',
 'Great@40',
 'jacky123!',
 'QQqq11!!1',
 '1q2w3e!Q@W#E',
 'foxfire=150',
 'peepie#3',
 'banana#13',
 'Parker1!',
 'abudhabi@1',
 'ralph*1',
 '$earay230',
 '666xxx$',
 'InD@1947',
 'roger@21',
 '@nkur#12',
 'mankanali123#',
 'Birdman31%',
 'FloaTers*01$',
 'brA*hef3',
 'somnath_123',
 '))))44aabc',
 '100%sean',
 '@lterN8',
 'maybi69.',
 'nothere8*',
 'manisha!1',
 'Jskr!975Hmkr',
 '*eja2600',
 'ROse!@34tw',
 'gsx-r750',
 'le_corbu2000',
 'Shawns1!',
 '#Apple123#',
 '10.35.2.12',
 '*2001DodgeSLT!',
 'korea00$',
 'thomas#13',
 'Fj0shuA!',
 'dr90pl:m',
 ')OKMmko0',
 '0.12345',
 'apr_oct5768',
 'nikolas@02',
 'madhu_99',
 'H0b0ken!',
 'zoom_2716',
 'Fr33@g@in',
 '1ltf@ep.',
 'dav123!',
 '$4fatcat',
 'expo_27',
 'WM-525SB',
 'Blackhawk5.5',
 '16feb@1968',
 'jlcGRC51213*',
 'G0TampaBuc$',
 'fuck@123',
 '(mmsop1)',
 '#Semi99!',
 'pa@sw06d',
 'sa&iprp123',
 'dre.dre4life',
 'simbacat9$',
 '454-2523',
 '&KRars19',
 'adk_1976',
 'kr$1970',
 'Stopsign01!',
 'sp@rrow5',
 'conejo-23',
 '#$88PEnnyb',
 'may1988@',
 'AE1965&1967',
 'samsung#45',
 'jackson05#',
 'Cry5t@!24',
 'Bosco69$$',
 'khali1!',
 'p@ntheR1995',
 'm@r1ll10n',
 'honey-4-u',
 'ihategirls-65',
 '1qazZAQ!1!',
 'gem0-8take123',
 'RfRb4e*11',
 'kvc0730#',
 'rpassr$123',
 'Dana@718',
 'ZAQ!2wsx',
 'xhjk51asd6@',
 'Pa$$word01!',
 'rfreeman 10@',
 '0715!_0119',
 'Romeao24!',
 '1#2lover19',
 'omea_2007',
 'P&CSex4',
 'iloveyou_8',
 'L1sa3i4i**9',
 '654321..',
 'kyann_1',
 'Ran3er175?',
 'Nid123!',
 'Steelcouch387@',
 'matrix_09',
 '0SoLonely!',
 'simple1!',
 'k9r2d24u$',
 '!EEC44eec!',
 'l_789456',
 'TecH1922#$',
 'HOLTv!ll3',
 '#1FANOFMEUC',
 'guess-2',
 'Todo-123',
 'runk88**',
 'kunu123#1',
 'pass.word7',
 'lovio@1',
 'sage#44',
 'supplymee-14',
 'hinojos@20',
 '522-3576',
 'tennis3.5',
 'soccer@2',
 'M@04Rise',
 'JE$$ica1204',
 'jk0-32057',
 '<ak47-rules>',
 'nbdkja12637!',
 'in_trouble2003',
 'Stlpizza#1',
 'dinesh@133',
 'Qwedsa123!',
 '7t32-7d19',
 'Forrest2@',
 'E30bmw325!',
 '(fuck1n)',
 'Kane875!',
 'eVil32b_b',
 'DAVID19.',
 '1nhLori!',
 ':)J&J:)8',
 '&\\E7_&\\E7\\E7_',
 "woody's#1",
 '2_manycats',
 'Pikake#1',
 'Wendys2800!',
 '$amsung1',
 'bvc123!!',
 'prec!se!65',
 'hokiesr#1',
 '$uperman1',
 'Dr.wit1',
 'ddmmallin1.',
 'Anne1luv!',
 'rongila6$',
 'phjlplal_1911',
 'peyton_18',
 'budlight#1',
 'Netw0rk!',
 'wi>812lco',
 '324-8531',
 'Mus!kman1127',
 'rachel#1',
 'PA$$word01',
 'T1.5m244',
 ']Inter@Dev6.',
 'SHIThead99@@',
 'test10!',
 'pala_9840',
 'JESUS13*',
 'graderman_1',
 'derrek*1237',
 'virgo@85',
 'Jade/2004',
 'redplanet-01',
 'mike23!!',
 'D0wnGyp$y757',
 '#noori1#',
 '4ever&2',
 'd-blocko8',
 '99178-NA',
 'spark@1282',
 'anant@123',
 '$$Tab1308',
 'kiss98.5',
 'jed3rd_dp',
 'teggun1!',
 '31122000..',
 'jimmy826@#1',
 'teresa13!',
 'demonic-95',
 'vb$0013',
 'FRIENDS@1979',
 'ventus06$',
 'jack$on7',
 'WLCNCO_28',
 'Jazz12!',
 'dabrowa@53',
 'Boingo_1',
 '8952089Laz:)!',
 'secret.007',
 'Love@143',
 '1989_100',
 'DoubleA82*@',
 'P0werB0%',
 'Marine1!',
 'cj7669mm!!',
 'mark_2912',
 'abcde_123',
 '4-WHEELER',
 'cb 12 01.',
 'styler-404',
 'luv_yah2',
 'frank4bes2003!!',
 'S@bres06',
 'bh.m.143',
 '2002wrx$',
 'creatin1$',
 '4545_pop',
 '_1975-saroja',
 '4swingin!',
 '2956667-s',
 'haniya@1',
 'maxpayne@1',
 'BeeBop69*',
 'i12bnak!',
 'b&b2001',
 '1/yamahar1',
 'death@666',
 'passw0rd!',
 'Utah_17',
 '@#F@#djwh3',
 '13_blue',
 'volcano1!',
 'T&L1015',
 'Te@cheR01!',
 'sexyN43*',
 'Wintertime5%',
 '146143@aol.com',
 '7_1_5_6_3',
 'bitta123*',
 'bigdog101/2',
 'olasgrandes.1',
 'taken.740',
 'lfc___09',
 'jai_5788',
 'aedlcn07!',
 'jmcddec#1',
 '143376*!Now',
 '341-5170',
 'Barrymore9!',
 'aidualc_18',
 'justice777$',
 'D1cK@ns#29',
 'gat0rs#1',
 'lilly/9703',
 'B!t(H4e&*R',
 'bila.bila30',
 'sexy_1967',
 'abcd!!!1',
 'M@#445#',
 'wilson#3',
 '67LONGPOLE^',
 'nine1/2',
 'tara01231973*',
 '778299!',
 'qwe789@@',
 'Kyl3teddi98!',
 '1@@@#$%^',
 'butter06$',
 'Aa1@zeta',
 'del7498$',
 'keajkj#2',
 'My02*girls',
 'special#56',
 'QW!@er345',
 'Dm1956!',
 'spin960&&',
 'cwm@2009',
 'danny001!',
 'P@ssWord11*',
 "qa'/4562",
 '$$RFV55tgb',
 'Kanna!43',
 'resin8!',
 'WarriorMMA#2',
 'N1chol@s',
 'Hbi_4tPD7',
 'Fr3@kyS3x',
 'Msbu@123',
 'flo..123',
 'poonam123$',
 'Hopeful!90',
 'sennam',
 '1918ford',
 '609880',
 'daniel0605',
 'bigshow0',
 'cheeks',
 'chris0423',
 'iquit',
 'cpu',
 'laurence',
 'Vanilla',
 '1dragon2',
 'fras13r',
 'sankri32',
 'rex1232',
 'prudvi',
 'plplplpl',
 'Indur9900',
 'saysuin09',
 'smithi',
 'dodgesst',
 'simple770',
 '1suckmedry',
 'bigasscash',
 'life65',
 'custersd',
 'aviators',
 'pn21vo369',
 'pokusaj',
 'Studio1',
 '7898789',
 'eugenem',
 'uppup',
 'nacha',
 '6600',
 'becky664',
 'sailaway',
 'jon513',
 'susehpe',
 'davisdog',
 'ISTRC',
 'thematrix',
 'cubs03',
 'boblover',
 '5831481ec',
 'chimaobimi',
 'musspuss',
 'pauldavid',
 '63726372',
 'syndrome',
 'judied',
 'johnny11',
 'alison3',
 'limberger',
 'geneciborges',
 '11mike',
 'styx',
 'armyrnnc',
 'bonein',
 'qwx123',
 'sh25291',
 'octahedron',
 'chevy',
 'iamsmart',
 'showme83',
 'swingthing',
 '501502',
 '165',
 'shayman',
 'mrmiko',
 'bibijan1',
 'baxter01',
 '666SOULCRUSHER',
 'd7634377',
 'ow6311',
 '042683arking',
 'Sept1449',
 'crobin',
 '90900',
 'puffy35720',
 '007JAMROCK',
 'pchpch',
 'tosharobby1',
 'vijaykumar',
 '102243',
 'PPAULA',
 'moose2',
 'albannach',
 'mypunk',
 'gwafc12',
 'baskett',
 'bighitter',
 'n221tb',
 'doclove78',
 'maggie15',
 'moosepotter',
 'boddah',
 'zah123id',
 'didpix1628',
 'flirtin1',
 'foosball',
 'maliah05',
 'susan',
 'rl11704',
 'bubsy',
 '333097',
 'dizydan',
 'kimble',
 'phantoom',
 'emtchester',
 'chevy99',
 'travisrm',
 'notme6969',
 'feyenoord',
 'mark1104',
 'swinger25',
 'adebayo34',
 'bell1034',
 'padult',
 '111ayush',
 'jazzman',
 '691992',
 'garg12',
 'fisherp2',
 'xyzabc67',
 'eh007',
 '7elena',
 'missysammy',
 'ccc999',
 'eg49002',
 'downtime5',
 'love6977',
 'lois',
 '4141288',
 'ayodeji',
 '1trustme',
 'xbox1109',
 'wiutennis',
 'placer13420',
 'bunny523',
 'alpaca1969',
 'Jericho941',
 'jaden7',
 'fishbelly',
 'PVANCE',
 '2timer',
 'Italian303',
 'burlsink82',
 'nasfan',
 'sockeye009',
 '30513051',
 'tesla69',
 'tw65667',
 'BIGBEAR25',
 'jalc13',
 'Mash4077x',
 'xes27yyy',
 'legacyanjali',
 'jalesa21',
 'pleasedome',
 'catdcatd',
 'joseph93',
 'camaro75',
 'boybad',
 '14449',
 'BoppScott',
 'suckthis',
 'down11',
 'dad42169',
 'gemini6262',
 '9494949494',
 'cameronbay',
 'carlajean',
 'luv2danc',
 'cuddly',
 '2013286',
 '3938jd',
 'aizelaizel',
 'smudge',
 'steelman22',
 'mrwiggles',
 'garvinpk',
 'bianca19',
 'swtmtty',
 '489441',
 'usmcmc',
 'horst',
 '2832389',
 '404fun2',
 'zm561111',
 'illini1984',
 'padua78',
 'cb47900',
 'ESHAMNATAS',
 'mtc201',
 '28552855',
 'Dek01201',
 'poppie69',
 '21152115',
 'timpwfsnc',
 'adebola1',
 'kb12052',
 '444200',
 '750ace',
 'distrust',
 'cyotee',
 'destiny8',
 'brittini',
 'tonycat73',
 'hdharley',
 'mclamb',
 'ROSEANN',
 'lgg44rr39',
 'golf87',
 '70602',
 'chulkas69',
 'cahill',
 '279223',
 'ihavenut',
 'gemini42',
 'jyoti9339',
 'tortopussy',
 'yankees237',
 'maddymech',
 'ghetolife',
 'zangya',
 'rahven6',
 'Printer1220',
 'bates509',
 's9006239',
 '24802480',
 'hamdog',
 'otis68',
 'hungguy111',
 'padlock',
 '86720',
 '167201',
 'alanford',
 '43264326',
 'banks76',
 'green85',
 'tisha11',
 'danielle71',
 'herdfans',
 'picturefan',
 'sanamas',
 'dmxdmx',
 '280685',
 '231508',
 'freedays4u',
 'M5UW3',
 'cmd1949',
 '320master',
 '265265',
 '959595',
 'demon153',
 'z1pp3r',
 'lati',
 'victoria94',
 'funtobewith',
 'donkyjon',
 'jimbobs1',
 'tech0027',
 '92masters',
 'besmart',
 'kukenn',
 'knapp1',
 'technologist',
 'riley01',
 'noah2008',
 '9392680292',
 'joeflu',
 'laguito',
 '11141114',
 'mik79ohn',
 'chief7447',
 'pelt',
 '5853912',
 'sagar1234',
 'sami245',
 'gmangman',
 'halo4',
 'pointer10',
 'paige00',
 'huskerdu3',
 'whyyes',
 'love1979',
 'Harley707',
 'willbeck',
 'bobafett64',
 '15191519',
 'cajunbaby',
 'jakjor12',
 'lynnsean',
 'whitewater',
 'ah3000',
 '2584052',
 'mitose',
 'martybg',
 'eddie42',
 'picks',
 'beemercat',
 'rhiannon',
 'mymymy1',
 '2457sager',
 'gralt',
 'zanfou',
 'hardball',
 'elliot12345',
 'spanky13',
 'Moeller1',
 '5511',
 'hotsuny',
 'marcus28',
 'still;one',
 'Sugarbuzz1',
 'mustanglx',
 'puppiedog',
 'thanos',
 'fuckchicks',
 'ummagumma',
 'krc1971',
 'antares7',
 ...]

In [81]:
data = pd.DataFrame(lines, columns=['Lines'])

In [82]:
data.describe()

           Lines
count     414506
unique    375853
top     lisa6/29
freq           4

In [83]:
data = data.drop_duplicates()

In [84]:
data.describe()

            Lines
count      375853
unique     375853
top     rlkj@1980
freq            1

In [85]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 375853 entries, 0 to 376825
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Lines   375853 non-null  object
dtypes: object(1)
memory usage: 5.7+ MB

In [89]:
lines = data['Lines'].to_list()
lines

['rlkj@1980',
 'tp@12345678',
 'M!$$y2005',
 'IM1n1raq!!',
 'n#wlif07',
 'acorn123!',
 '521@843',
 '500049@vikas',
 'Ranger#2',
 'sw33tb@by',
 'dod896@l1',
 'India@123456',
 'tvicky_38',
 '55296 -',
 'adr_123',
 '5.bigdog.6',
 'Por$c#301',
 'Jay1026.',
 'queens-08',
 'Ma%%32Fn',
 '12-guage',
 'Slvr540!!',
 'Aziza@444',
 'xyzzy@42',
 'ABcd!@3456',
 '141414!',
 '!7Eezbutz',
 'komal@1889',
 'atl678*',
 'sarabeee#0',
 'aghg.d]hk123',
 'Max$56li',
 'lexi01*',
 'spike10^',
 'riz_123',
 '*mineonly1',
 'fucker-8',
 'v-dogg651',
 'nannu_333',
 'shift_1',
 'yankee1!',
 '@>-; j2',
 'JAIMINE.18301',
 'Hmfogtliwt1!',
 'vmfa=332',
 'Randy&Ann1',
 '1qaz@WSX3edc',
 '$ow3ll01',
 'dilldo_41364',
 'n@t@li3',
 'mustang87*',
 'maxie_115',
 '69longpole^',
 'ang#1010',
 '12!@asAS2',
 '*deniro321*',
 'integra_11',
 '06.08.74',
 '111111a/b',
 '$rwm1446',
 'Yz250cc!',
 'EL.rjel.78',
 'b@dbon352',
 '390fs((@*',
 'supri@24',
 'St3mmen/',
 'N1chola$',
 'MGoyet57^$',
 'Massive1!',
 '$up3rm2n69',
 'P@$$w0rd',
 '430WRANSOM*',
 '$1dexter',
 'Mindy777!',
 'BADASSBOSS1.',
 'bjme69*',
 'vicho_12',
 'kimmy@91',
 'hz9824$$77',
 '*pkdll79',
 'hgregs5@hotmail',
 '`1- equals `1- equals',
 '200000**',
 'zaiba*786',
 'Keg99!!',
 'Mash_217',
 '!234Qwer',
 '#o9bawl2g0',
 'ibtrg_05',
 'Q1w2E3r4)',
 'DCwhat#1',
 '#1Gangster',
 'lled83!',
 'subodh.com23',
 'Defygravity#4',
 'Mwss1722!',
 'luvvvv.1',
 '(wolf)69',
 'Pa$$word11',
 'purush@9',
 'r2!@roya',
 'samoth@22',
 'abhinav$08',
 '!JM4223jm!',
 'khush@24ab',
 'DAwn2538!!',
 'TsL0404**',
 'ric_rock63',
 'amber04@',
 'idiot@123',
 'munaiba.23',
 'Carol1985$$$',
 'hockey4life!',
 'abc123@',
 'tacoma#12',
 'love143143*',
 '$cotL4nd',
 'Red0078!',
 'Kfce!525',
 '2212@fire',
 'maruti.3639',
 'qwerty#1',
 'Tommy#1',
 '#811gpd',
 'pyyhx#1',
 'camcam_09',
 '6969)()()(',
 'leska_0215',
 'NM0x!ey1n',
 'don@2003',
 '$R0adRa!l',
 'CCllmm81!!',
 '*p#1672!',
 'fab5bros.',
 'Dmlss%30',
 '1234$abc',
 'tepas8586@123',
 'tamokce56.25',
 'seema!1',
 'Shawn#36',
 'Ah$511977',
 'ac/dc43122',
 '#1hottie',
 '2007-08',
 'A11is0n@',
 '1234@abcd',
 'Cowboys#1',
 'rolnosik_39',
 'fazuha@143',
 '2RDK4Men*',
 'Firedawgs10!',
 '**JH55ds',
 'df45DF$%',
 'Db3**1234',
 'ewei^4TR',
 '91-zephyr',
 '12345ama@',
 'moscow01!',
 'lance2lot#',
 'i8@cbgbs',
 '456%sexy',
 '!1bigkahuna',
 '24aug88@$',
 'W@ndagr8',
 'dragon!1',
 'chicano4?',
 '@ROSE1234',
 'fun.123',
 'shawna_1',
 'cathym1#',
 'pa28-180',
 'medo.01',
 'Skooter71$',
 'chint00$',
 'Microsoft123!',
 'Jimmy22!',
 'Iailwm2c1!',
 'bettisy-boy5',
 'R0Dgerth@!',
 '9$ether',
 'M@cEt0wn!',
 'm@dhur40i',
 'trista_03',
 'c00L1#?mAN',
 'swingtown@11',
 'lavecious16-alr',
 'qH3M;Ppp',
 'Ghar*usa2',
 ';outu4458',
 '11ju1994_11ju94',
 'Mca333d@',
 '2wsx@WSX',
 'Rsa21oct85$',
 'red#2008',
 'equator@1',
 'larry/mary3',
 'bu*res.29',
 '82870002.Hkem',
 'goldfish1!',
 'Err:520',
 'kombucha95%',
 'Ilgeah*1965',
 'property925@',
 'men@123',
 '123456@78',
 'spf23@yahoo.com',
 'tps@970',
 'sh@wn66',
 '94639-44149',
 'Ramona!84',
 'JUNE233/',
 'I<3LB2def',
 'tt&atti2dd',
 'Rama.l11',
 '5david$$',
 'c@ndyc0rn',
 'fuckYou2$ME',
 'asd123.',
 'mouc@143',
 '^YHN9ol.',
 'zaq1@WSX',
 'KBrandon!#fox30',
 '7yhnMJU^',
 'halo-1903',
 'jBy&m87',
 '?06rbpy?',
 '15V@ndalia',
 'f@c3tim3',
 '1234!@#$a',
 'hater123!',
 'ahabs_99',
 'TRoy40$$',
 'jesseno.1',
 '12.11.74',
 '275/40/20',
 'dalejr#8',
 '76-2o0s0u2a',
 'M1keyb-1969',
 'buddy123*',
 'bru!va08',
 '!Pass1234',
 'Mandy@82',
 'kaais_86',
 'pot_420',
 'bipi@123',
 '!QAZxsw2',
 'BudR1z0r!!',
 'Dozzer45*',
 'Kz@92Q*>',
 'K1ttyC@T',
 '6yhn9ol.',
 'p!p32008',
 'CR08#$sr',
 'F0ufcfk!',
 '2403@doniztss',
 'live4God!',
 'pascode150!',
 'psi.1234',
 'april12345%%%',
 'in-1289',
 'lilangie#44',
 'mountain!1',
 'R@N#er45!',
 'Monkey1!',
 'happy!7777',
 'Bubba#456',
 '@ries21',
 '#10jessy',
 'boswell#1',
 'newlife0-1',
 'Splinky#69',
 '##Laverne1$',
 'sukoi123$',
 '21.613.138',
 'kia12345%%',
 'LONGINUS_14',
 '%c0tt543',
 'ngf0607!',
 'lucky2503!',
 'hojo34*',
 'calif_cpl2001',
 '44kats!2',
 'boss143*',
 'ilha&69',
 'rum@t80!YO',
 'max002@',
 'j3ffr3y98-bailey',
 'bamaboy#1',
 'clint4268!',
 'Purple.123',
 'bigal#87',
 'qotsa1978!@',
 'mjmj@06',
 'manoj*28',
 'jeiger#24',
 'Suryam_1985',
 'dave@dave1',
 'rocking_193',
 'reyess_88',
 'kelvic_13',
 'imakat0653@yahoo.com',
 'susilar$84',
 'summer@69',
 'Jskr!975',
 'location-s1',
 'Brooke*1',
 'fuckunow$5',
 'Ch!ck3ns',
 'sar03ge#1',
 'TTking74$$',
 'lovers123*',
 'rna.252',
 'dlm@15937',
 'black_c0ck',
 'rfg-0800',
 'dwl@1320',
 '..  09125875162',
 'Bulldog89*',
 'Kingbud#1',
 'jatt123@',
 'iloveronan23!',
 'matcu-69',
 'Smurf.74',
 'baseball#1',
 'sambo_el_11',
 '##army89',
 'no1is@@',
 'KRtr4454#',
 'REbecca!@34',
 'B@ubacart1',
 '#EDC4rfv',
 '138*438',
 '11yhtak*',
 'usmc_3075',
 '!Dalejr88',
 'henley*1',
 'Aczs@b#4',
 'coldwell1*',
 'sunils$0',
 'p@ssw0rd',
 '300resumes?',
 'monse12@',
 'TellNo1!',
 '118241$',
 'ORLY1-9-59',
 'moNTan34#$',
 '021869*',
 'Bi@Tch72',
 'jb-90252',
 'H&H5050',
 'snow*03',
 '1Spyder.',
 '$secco77a',
 'P@ssword8',
 'US.army.44',
 'salhji45*',
 '02Bdays2#',
 '$imple6',
 'ab1g@il',
 'durango_12',
 'ssmsswjw@1',
 '987654321!',
 'neeru47301@',
 '496/6206',
 'b@ndit04',
 'BuckI208!!',
 '9o0p(O)P',
 '$4licks',
 'M4ld1ves@123',
 '4getmenot.hs',
 '17candle000$',
 'Dolphin.1',
 'viking2-7',
 '96JPcher#1',
 '#2always',
 '21L-TL-T',
 '5.7cross',
 'bombay@123',
 'Kill$20',
 'spice_1',
 '*Try08*',
 'makayla3*',
 'Great@40',
 'jacky123!',
 'QQqq11!!1',
 '1q2w3e!Q@W#E',
 'foxfire=150',
 'peepie#3',
 'banana#13',
 'Parker1!',
 'abudhabi@1',
 'ralph*1',
 '$earay230',
 '666xxx$',
 'InD@1947',
 'roger@21',
 '@nkur#12',
 'mankanali123#',
 'Birdman31%',
 'FloaTers*01$',
 'brA*hef3',
 'somnath_123',
 '))))44aabc',
 '100%sean',
 '@lterN8',
 'maybi69.',
 'nothere8*',
 'manisha!1',
 'Jskr!975Hmkr',
 '*eja2600',
 'ROse!@34tw',
 'gsx-r750',
 'le_corbu2000',
 'Shawns1!',
 '#Apple123#',
 '10.35.2.12',
 '*2001DodgeSLT!',
 'korea00$',
 'thomas#13',
 'Fj0shuA!',
 'dr90pl:m',
 ')OKMmko0',
 '0.12345',
 'apr_oct5768',
 'nikolas@02',
 'madhu_99',
 'H0b0ken!',
 'zoom_2716',
 'Fr33@g@in',
 '1ltf@ep.',
 'dav123!',
 '$4fatcat',
 'expo_27',
 'WM-525SB',
 'Blackhawk5.5',
 '16feb@1968',
 'jlcGRC51213*',
 'G0TampaBuc$',
 'fuck@123',
 '(mmsop1)',
 '#Semi99!',
 'pa@sw06d',
 'sa&iprp123',
 'dre.dre4life',
 'simbacat9$',
 '454-2523',
 '&KRars19',
 'adk_1976',
 'kr$1970',
 'Stopsign01!',
 'sp@rrow5',
 'conejo-23',
 '#$88PEnnyb',
 'may1988@',
 'AE1965&1967',
 'samsung#45',
 'jackson05#',
 'Cry5t@!24',
 'Bosco69$$',
 'khali1!',
 'p@ntheR1995',
 'm@r1ll10n',
 'honey-4-u',
 'ihategirls-65',
 '1qazZAQ!1!',
 'gem0-8take123',
 'RfRb4e*11',
 'kvc0730#',
 'rpassr$123',
 'Dana@718',
 'ZAQ!2wsx',
 'xhjk51asd6@',
 'Pa$$word01!',
 'rfreeman 10@',
 '0715!_0119',
 'Romeao24!',
 '1#2lover19',
 'omea_2007',
 'P&CSex4',
 'iloveyou_8',
 'L1sa3i4i**9',
 '654321..',
 'kyann_1',
 'Ran3er175?',
 'Nid123!',
 'Steelcouch387@',
 'matrix_09',
 '0SoLonely!',
 'simple1!',
 'k9r2d24u$',
 '!EEC44eec!',
 'l_789456',
 'TecH1922#$',
 'HOLTv!ll3',
 '#1FANOFMEUC',
 'guess-2',
 'Todo-123',
 'runk88**',
 'kunu123#1',
 'pass.word7',
 'lovio@1',
 'sage#44',
 'supplymee-14',
 'hinojos@20',
 '522-3576',
 'tennis3.5',
 'soccer@2',
 'M@04Rise',
 'JE$$ica1204',
 'jk0-32057',
 '<ak47-rules>',
 'nbdkja12637!',
 'in_trouble2003',
 'Stlpizza#1',
 'dinesh@133',
 'Qwedsa123!',
 '7t32-7d19',
 'Forrest2@',
 'E30bmw325!',
 '(fuck1n)',
 'Kane875!',
 'eVil32b_b',
 'DAVID19.',
 '1nhLori!',
 ':)J&J:)8',
 '&\\E7_&\\E7\\E7_',
 "woody's#1",
 '2_manycats',
 'Pikake#1',
 'Wendys2800!',
 '$amsung1',
 'bvc123!!',
 'prec!se!65',
 'hokiesr#1',
 '$uperman1',
 'Dr.wit1',
 'ddmmallin1.',
 'Anne1luv!',
 'rongila6$',
 'phjlplal_1911',
 'peyton_18',
 'budlight#1',
 'Netw0rk!',
 'wi>812lco',
 '324-8531',
 'Mus!kman1127',
 'rachel#1',
 'PA$$word01',
 'T1.5m244',
 ']Inter@Dev6.',
 'SHIThead99@@',
 'test10!',
 'pala_9840',
 'JESUS13*',
 'graderman_1',
 'derrek*1237',
 'virgo@85',
 'Jade/2004',
 'redplanet-01',
 'mike23!!',
 'D0wnGyp$y757',
 '#noori1#',
 '4ever&2',
 'd-blocko8',
 '99178-NA',
 'spark@1282',
 'anant@123',
 '$$Tab1308',
 'kiss98.5',
 'jed3rd_dp',
 'teggun1!',
 '31122000..',
 'jimmy826@#1',
 'teresa13!',
 'demonic-95',
 'vb$0013',
 'FRIENDS@1979',
 'ventus06$',
 'jack$on7',
 'WLCNCO_28',
 'Jazz12!',
 'dabrowa@53',
 'Boingo_1',
 '8952089Laz:)!',
 'secret.007',
 'Love@143',
 '1989_100',
 'DoubleA82*@',
 'P0werB0%',
 'Marine1!',
 'cj7669mm!!',
 'mark_2912',
 'abcde_123',
 '4-WHEELER',
 'cb 12 01.',
 'styler-404',
 'luv_yah2',
 'frank4bes2003!!',
 'S@bres06',
 'bh.m.143',
 '2002wrx$',
 'creatin1$',
 '4545_pop',
 '_1975-saroja',
 '4swingin!',
 '2956667-s',
 'haniya@1',
 'maxpayne@1',
 'BeeBop69*',
 'i12bnak!',
 'b&b2001',
 '1/yamahar1',
 'death@666',
 'passw0rd!',
 'Utah_17',
 '@#F@#djwh3',
 '13_blue',
 'volcano1!',
 'T&L1015',
 'Te@cheR01!',
 'sexyN43*',
 'Wintertime5%',
 '146143@aol.com',
 '7_1_5_6_3',
 'bitta123*',
 'bigdog101/2',
 'olasgrandes.1',
 'taken.740',
 'lfc___09',
 'jai_5788',
 'aedlcn07!',
 'jmcddec#1',
 '143376*!Now',
 '341-5170',
 'Barrymore9!',
 'aidualc_18',
 'justice777$',
 'D1cK@ns#29',
 'gat0rs#1',
 'lilly/9703',
 'B!t(H4e&*R',
 'bila.bila30',
 'sexy_1967',
 'abcd!!!1',
 'M@#445#',
 'wilson#3',
 '67LONGPOLE^',
 'nine1/2',
 'tara01231973*',
 '778299!',
 'qwe789@@',
 'Kyl3teddi98!',
 '1@@@#$%^',
 'butter06$',
 'Aa1@zeta',
 'del7498$',
 'keajkj#2',
 'My02*girls',
 'special#56',
 'QW!@er345',
 'Dm1956!',
 'spin960&&',
 'cwm@2009',
 'danny001!',
 'P@ssWord11*',
 "qa'/4562",
 '$$RFV55tgb',
 'Kanna!43',
 'resin8!',
 'WarriorMMA#2',
 'N1chol@s',
 'Hbi_4tPD7',
 'Fr3@kyS3x',
 'Msbu@123',
 'flo..123',
 'poonam123$',
 'Hopeful!90',
 'sennam',
 '1918ford',
 '609880',
 'daniel0605',
 'bigshow0',
 'cheeks',
 'chris0423',
 'iquit',
 'cpu',
 'laurence',
 'Vanilla',
 '1dragon2',
 'fras13r',
 'sankri32',
 'rex1232',
 'prudvi',
 'plplplpl',
 'Indur9900',
 'saysuin09',
 'smithi',
 'dodgesst',
 'simple770',
 '1suckmedry',
 'bigasscash',
 'life65',
 'custersd',
 'aviators',
 'pn21vo369',
 'pokusaj',
 'Studio1',
 '7898789',
 'eugenem',
 'uppup',
 'nacha',
 '6600',
 'becky664',
 'sailaway',
 'jon513',
 'susehpe',
 'davisdog',
 'ISTRC',
 'thematrix',
 'cubs03',
 'boblover',
 '5831481ec',
 'chimaobimi',
 'musspuss',
 'pauldavid',
 '63726372',
 'syndrome',
 'judied',
 'johnny11',
 'alison3',
 'limberger',
 'geneciborges',
 '11mike',
 'styx',
 'armyrnnc',
 'bonein',
 'qwx123',
 'sh25291',
 'octahedron',
 'chevy',
 'iamsmart',
 'showme83',
 'swingthing',
 '501502',
 '165',
 'shayman',
 'mrmiko',
 'bibijan1',
 'baxter01',
 '666SOULCRUSHER',
 'd7634377',
 'ow6311',
 '042683arking',
 'Sept1449',
 'crobin',
 '90900',
 'puffy35720',
 '007JAMROCK',
 'pchpch',
 'tosharobby1',
 'vijaykumar',
 '102243',
 'PPAULA',
 'moose2',
 'albannach',
 'mypunk',
 'gwafc12',
 'baskett',
 'bighitter',
 'n221tb',
 'doclove78',
 'maggie15',
 'moosepotter',
 'boddah',
 'zah123id',
 'didpix1628',
 'flirtin1',
 'foosball',
 'maliah05',
 'susan',
 'rl11704',
 'bubsy',
 '333097',
 'dizydan',
 'kimble',
 'phantoom',
 'emtchester',
 'chevy99',
 'travisrm',
 'notme6969',
 'feyenoord',
 'mark1104',
 'swinger25',
 'adebayo34',
 'bell1034',
 'padult',
 '111ayush',
 'jazzman',
 '691992',
 'garg12',
 'fisherp2',
 'xyzabc67',
 'eh007',
 '7elena',
 'missysammy',
 'ccc999',
 'eg49002',
 'downtime5',
 'love6977',
 'lois',
 '4141288',
 'ayodeji',
 '1trustme',
 'xbox1109',
 'wiutennis',
 'placer13420',
 'bunny523',
 'alpaca1969',
 'Jericho941',
 'jaden7',
 'fishbelly',
 'PVANCE',
 '2timer',
 'Italian303',
 'burlsink82',
 'nasfan',
 'sockeye009',
 '30513051',
 'tesla69',
 'tw65667',
 'BIGBEAR25',
 'jalc13',
 'Mash4077x',
 'xes27yyy',
 'legacyanjali',
 'jalesa21',
 'pleasedome',
 'catdcatd',
 'joseph93',
 'camaro75',
 'boybad',
 '14449',
 'BoppScott',
 'suckthis',
 'down11',
 'dad42169',
 'gemini6262',
 '9494949494',
 'cameronbay',
 'carlajean',
 'luv2danc',
 'cuddly',
 '2013286',
 '3938jd',
 'aizelaizel',
 'smudge',
 'steelman22',
 'mrwiggles',
 'garvinpk',
 'bianca19',
 'swtmtty',
 '489441',
 'usmcmc',
 'horst',
 '2832389',
 '404fun2',
 'zm561111',
 'illini1984',
 'padua78',
 'cb47900',
 'ESHAMNATAS',
 'mtc201',
 '28552855',
 'Dek01201',
 'poppie69',
 '21152115',
 'timpwfsnc',
 'adebola1',
 'kb12052',
 '444200',
 '750ace',
 'distrust',
 'cyotee',
 'destiny8',
 'brittini',
 'tonycat73',
 'hdharley',
 'mclamb',
 'ROSEANN',
 'lgg44rr39',
 'golf87',
 '70602',
 'chulkas69',
 'cahill',
 '279223',
 'ihavenut',
 'gemini42',
 'jyoti9339',
 'tortopussy',
 'yankees237',
 'maddymech',
 'ghetolife',
 'zangya',
 'rahven6',
 'Printer1220',
 'bates509',
 's9006239',
 '24802480',
 'hamdog',
 'otis68',
 'hungguy111',
 'padlock',
 '86720',
 '167201',
 'alanford',
 '43264326',
 'banks76',
 'green85',
 'tisha11',
 'danielle71',
 'herdfans',
 'picturefan',
 'sanamas',
 'dmxdmx',
 '280685',
 '231508',
 'freedays4u',
 'M5UW3',
 'cmd1949',
 '320master',
 '265265',
 '959595',
 'demon153',
 'z1pp3r',
 'lati',
 'victoria94',
 'funtobewith',
 'donkyjon',
 'jimbobs1',
 'tech0027',
 '92masters',
 'besmart',
 'kukenn',
 'knapp1',
 'technologist',
 'riley01',
 'noah2008',
 '9392680292',
 'joeflu',
 'laguito',
 '11141114',
 'mik79ohn',
 'chief7447',
 'pelt',
 '5853912',
 'sagar1234',
 'sami245',
 'gmangman',
 'halo4',
 'pointer10',
 'paige00',
 'huskerdu3',
 'whyyes',
 'love1979',
 'Harley707',
 'willbeck',
 'bobafett64',
 '15191519',
 'cajunbaby',
 'jakjor12',
 'lynnsean',
 'whitewater',
 'ah3000',
 '2584052',
 'mitose',
 'martybg',
 'eddie42',
 'picks',
 'beemercat',
 'rhiannon',
 'mymymy1',
 '2457sager',
 'gralt',
 'zanfou',
 'hardball',
 'elliot12345',
 'spanky13',
 'Moeller1',
 '5511',
 'hotsuny',
 'marcus28',
 'still;one',
 'Sugarbuzz1',
 'mustanglx',
 'puppiedog',
 'thanos',
 'fuckchicks',
 'ummagumma',
 'krc1971',
 'antares7',
 ...]

In [90]:
with open('all.txt', 'w') as filehandle:
    for listitem in lines:
        filehandle.write('%s\n' % listitem)

In [39]:
print(type(all_letters))

<class 'str'>